### ISSUE TITLE
Control Details highlighting fails in chrome

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall-vuetify#36]
Code highlighting fails in chrome, this is due to 
``` css
.v-application code {
  background-color: revert;
  color: revert;
  display: revert;
  font-size: revert;
  -webkit-box-shadow: revert;
  box-shadow: revert;
  border-radius: revert;
  white-space: auto;
  overflow-wrap: break-word;
  max-width: 100%;
}
```
revert is not supported in chrome
